name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main  # 'main' ブランチに push された際に実行

jobs:
  deploy:
    runs-on: ubuntu-latest  # 仮想環境として Ubuntu を使用

    steps:
      # 1. リポジトリをクローン
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js をセットアップ
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Node.js のバージョンを指定

      # 3. Clasp をインストール
      - name: Install Clasp
        run: npm install -g @google/clasp

      # 4. .clasprc.json を設定（GitHub Secretsを使用）
      - name: Set up .clasprc.json
        run: echo "${{ secrets.CLASP_CREDENTIALS }}" > ~/.clasprc.json

      # 5. .clasp.json を設定
      - name: Set up .clasp.json
        run: echo '{"scriptId":"${{ secrets.SCRIPT_ID }}","rootDir":"${{ github.workspace }}"}' > .clasp.json

      # 6. config.gs の生成（環境変数を利用して秘匿情報を設定）
      - name: Generate config.gs
        run: |
          echo "const CLIENT_ID = '${{ secrets.CLIENT_ID }}';" > config.js
          echo "const CLIENT_SECRET = '${{ secrets.CLIENT_SECRET }}';" >> config.js
          echo "const REFRESH_TOKEN_KEY = '${{ secrets.REFRESH_TOKEN_KEY }}';" >> config.js
          echo "const CHANNEL_ID = '${{ secrets.CHANNEL_ID }}';" >> config.js
          echo "const MAIL_TO = '${{ secrets.MAIL_TO }}';" >> config.js
          ls -a  # 現在のディレクトリの中身を確認（必要であればデバッグとして使用）
          cat ~/.clasprc.json
          cat .clasp.json
          cat config.js

      # 7. Google Cloud の認証情報をセット（サービスアカウントのJSON）
      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json

      # 8. Clasp ログイン（サービスアカウントを使用）
      - name: Log in to Clasp
        run: clasp login --creds /tmp/credentials.json

      # 9. Google Apps Script へのデプロイ
      - name: Deploy to GAS
        run: clasp push